"""Authenticated, isolated runtime state for each installed extension.

The token is a bearer credential generated by the extension. It is never an
account ID: only its SHA-256 digest is retained as the in-memory lookup key.
"""
from __future__ import annotations

import contextlib
import hashlib
import re
import time
from dataclasses import dataclass, field
from typing import Dict, Iterator

from .browser_bridge import BrowserBridge, reset_current_bridge, set_current_bridge
from .events import EventBus, reset_current_bus, set_current_bus
from .loop import Registry, reset_current_registry, set_current_registry


TOKEN_RE = re.compile(r"^[A-Za-z0-9_-]{43,128}$")


class InvalidSessionToken(ValueError):
    pass


@dataclass
class SessionRuntime:
    key: str
    bus: EventBus = field(default_factory=EventBus)
    bridge: BrowserBridge = field(default_factory=BrowserBridge)
    registry: Registry = field(default_factory=Registry)
    last_seen: float = field(default_factory=time.monotonic)

    @contextlib.contextmanager
    def activate(self) -> Iterator["SessionRuntime"]:
        bus_token = set_current_bus(self.bus)
        bridge_token = set_current_bridge(self.bridge)
        registry_token = set_current_registry(self.registry)
        self.last_seen = time.monotonic()
        try:
            yield self
        finally:
            reset_current_registry(registry_token)
            reset_current_bridge(bridge_token)
            reset_current_bus(bus_token)


class RuntimeManager:
    def __init__(self) -> None:
        self._sessions: Dict[str, SessionRuntime] = {}

    @staticmethod
    def token_key(token: str) -> str:
        if not TOKEN_RE.fullmatch(token or ""):
            raise InvalidSessionToken("missing or invalid session token")
        return hashlib.sha256(token.encode("utf-8")).hexdigest()

    def get(self, token: str) -> SessionRuntime:
        key = self.token_key(token)
        runtime = self._sessions.get(key)
        if runtime is None:
            runtime = SessionRuntime(key=key)
            self._sessions[key] = runtime
        runtime.last_seen = time.monotonic()
        return runtime

    @property
    def session_count(self) -> int:
        return len(self._sessions)


runtimes = RuntimeManager()
